name: Jazzy Documentation

on:
  push:
    branches: [ main ]

jobs:

  exec-jazzy:
    runs-on: macos-11

    steps:
    - name: Install Ninja
      run: brew install ninja

    - name: Install CMake
      run: brew install cmake
    
    - name: Clone Repository 
      uses: actions/checkout@v2
      with:
        repository: mipalgu/Machines
        path: Machines 

    - name: Build Machines
      run: |
        cd Machines
        swift build

    - name: Copy Readme.md and .jazzy.yaml
      run: |
        cp Machines/README.md .
        cp Machines/.jazzy.yaml .

    - name: Jazzy Action
      uses: sersoft-gmbh/swifty-docs-action@v1.2.0
      with:
        source: ${{github.workspace}}/Machines
        output: docs

    - name: Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true
